### ISSUE TITLE
Request: option for not using floating ip and use IP from os.networks to vagrant ssh the instance

### ISSUE THREAD

**Issue by lccheung** [ggiamarchi/vagrant-openstack-provider#194]
Depends on the OpenStack networking setup, floating ip and external network is not a must in OpenStack networking. User could still access (or ssh) the VM instance through private network if the private network is a provider network.

Since in current implementation of vagrant-openstack-provider, floating_ip or floating_ip_pool must be provided. Could we add a option for not using floating ip and use IP from os.networks to vagrant ssh the instance?

For example, below is part of my Vagrntfile:
os.networks           = [ 'MgmtNet' ]
could we using the IP assigned from MgmtNet for vagrant ssh? (any workaround on current implementation are welcome)

Regards,
Taurus

**Comment by julienvey** [comment]
Hi @lccheung 

`floating_ip` and `floating_ip_pool` are not mandatory anymore since version 0.5.0, see this issue #55

For the IP resolution (to ssh for instance), we are using this lines of code https://github.com/ggiamarchi/vagrant-openstack-provider/blob/master/source/lib/vagrant-openstack-provider/utils.rb#L8

What they do is: 
* Get all the IPs for the instance
* If one is of type `floating_ip`, we use it
* Otherwise, we choose the first IP available.

Can you share with us your full (obfuscated) Vagrantfile and maybe some logs if you have ?
Thanks

**Comment by ggiamarchi** [comment]
I have just tested on an OpenStack with flat networking using only `os.networks` and i didn't encounter any problem.

**Comment by lccheung** [comment]
@julienvey and @ggiamarchi Thanks for the information. It works and the behavior is deterministic if there's only one os.networks.

But when there're multiple networks in os.networks as below:
os.networks           = [ 'MgmtNet', 'MetadataNet' ]
The function get_ip_address in utils.rb always returning the IP from network 'MetadataNet', while I want the IP from MgmtNet. The behavior is the same if I swap the sequence in os.networks as below:
os.networks           = [ 'MetadataNet', 'MgmtNet' ]
I think it is because what you mean of "first IP" is the first IP in the network IP list returned by nova get details call

So which IP is returned becomes non-deterministic for the user of vagrant. Is it possible we can specify which os.network to get the IP for vagrant ssh?

**Comment by ggiamarchi** [comment]
I suggest to keep the Vagrantfile syntax unchanged and fix the implementation of the method [`get_ip_address`](https://github.com/ggiamarchi/vagrant-openstack-provider/blob/v0.6.0/source/lib/vagrant-openstack-provider/utils.rb#L12) to take the first network of the Vagrantfile array instead of the first in the nova response.

With the configuration
```ruby
os.networks = ['net-1', 'net-2']
```
`net-1` will be chosen.

And with the configuration
```ruby
os.networks = ['net-2', 'net-1']
```
`net-2` will be chosen.

@lccheung Does that makes sens for you ?

**Comment by lccheung** [comment]
Yes. It makes sense. Could I know when the fix will be released?

Regards,
Taurus

**Comment by ggiamarchi** [comment]
It will be included in the minor release [0.6.1](https://github.com/ggiamarchi/vagrant-openstack-provider/milestones/0.6.1) that will be finalized before the end of the next week.

**Comment by lccheung** [comment]
Good and thanks. Hope I could get the fix soon.

**Comment by ggiamarchi** [comment]
@lccheung The release 0.6.1 included the fix for this one is available.
