### ISSUE TITLE
Ruby needs to update json version

### ISSUE THREAD

**Issue by jayunit100** [ggiamarchi/vagrant-openstack-provider#236]
Newer ruby (2.2+) don't like json 1.7.7, rendering this plugin hard to install on fedora 22 and up.  Any easy workarounds for this ? I thought vagrant bundled ruby somehow but maybe it doesnt.

**Comment by ggiamarchi** [comment]
Vagrant itself is built for ruby [2.0.0 only](https://github.com/mitchellh/vagrant/blob/master/.travis.yml#L13). This is why it is not recommended to install vagrant using your package manager (i suppose you use `dnf`) because this vagrant package depends on ruby without specifying to version. And as you stated, on Fedora its ruby 2.2.

```bash
$ rpm -qpR vagrant-1.7.2-7.fc22.noarch.rpm
/bin/sh
/bin/sh
/usr/bin/env
bsdtar
curl
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
ruby
ruby(release)
ruby(rubygems) >= 1.3.6
rubygem(bundler) >= 1.5.2
rubygem(childprocess) >= 0.5.0
rubygem(erubis) >= 2.7.0
rubygem(hashicorp-checkpoint) >= 0.1.1
rubygem(i18n) >= 0.6.0
rubygem(listen) >= 2.7.1
rubygem(log4r)
rubygem(net-scp) >= 1.1.0
rubygem(net-sftp)
rubygem(net-ssh) >= 2.6.6
rubygem(nokogiri) >= 1.6
rubygem(rb-inotify)
rubygem(rest-client)
shadow-utils
```

The best way to install vagrant is to use the package provided on the vagrant website because in this one ruby 2.0.0 is embedded.

```bash
wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.rpm
rpm -i vagrant_1.7.2_x86_64.rpm
```

And here, we can see it does not depend on any system ruby dependencies. Much more reliable.

```bash
$ rpm -qpR vagrant_1.7.2_x86_64.rpm
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
```

**Comment by jayunit100** [comment]
Ah ok that's how I usually do it on fedora hence I never saw this

**Comment by strzibny** [comment]
> This is why it is not recommended to install vagrant using your package manager

As a maintainer of Vagrant in Fedora I disagree, it's actually recommended way and the only one supported by Fedora Project. It was done to offer superb installation of Vagrant with libvirt provider and its much easier to install and run.

See https://developer.fedoraproject.org/tools/vagrant/about.html.

**Comment by v1k0d3n** [comment]
so is there any solution? i think it's very misleading to say that Fedora users must not use their system package manager. i've been fighting this dependency issue for a couple of days before finally running into this issue; and I consider my google-foo to be pretty decent. i'm creating a Docker image with vagrant installed (along with this plugin) and this will cause issues during CI-CD. could there be a better way to resolve this issue?
