### ISSUE TITLE
Release 0.7.0 breaks vagrant-proxyconf plugin

### ISSUE THREAD

**Issue by tommoyer** [ggiamarchi/vagrant-openstack-provider#249]
When using 0.6.1 and vagrant-proxyconf (1.5.0 or 1.5.1) after the folder sync, the vagrant-proxyconf plugin is called to configure the proxy. With 0.7.0, vagrant-proxyconf is no longer called to configure the proxy.

**Comment by ggiamarchi** [comment]
Reading the vagrant-proxyconf source code, i guess the root cause is the same as #248. See https://github.com/tmatilai/vagrant-proxyconf/blob/v1.5.1/lib/vagrant-proxyconf/hook.rb#L11

**Comment by Sharpie** [comment]
This also breaks the `vagrant-hostmanager` plugin, which hooks into the default `Provision` action to update `/etc/hosts` across all running VMs.

What's the reason for using a custom `ProvisionWrapper` action? It appears to have the undocumented effect of substituting a `@@ssh_ip@@` argument in shell provisioners.

I'd prefer the option of using the built-in `Provision` action so that other plugins work.
