### ISSUE TITLE
Feature request: custom command to resync folders

### ISSUE THREAD

**Issue by jesusaurus** [ggiamarchi/vagrant-openstack-provider#342]
Since synced folders are rsync'd to the remote host, it would be useful to have a way to trigger another rsync run. Perhaps a new custom command like `vagrant openstack folder-sync <name>` or `vagrant rsync <name>` to push files to the host named <name>.

**Comment by ggiamarchi** [comment]
Since version 0.8.0 we moved from custom "synced folders" middleware to the standard vagrant middleware (https://github.com/ggiamarchi/vagrant-openstack-provider/pull/295). That means we won't implement anymore any feature regarding synced folder inside this plugin.

By the way, the feature you want already exists within vagrant itself. You can use `vagrant rsync` (https://www.vagrantup.com/docs/cli/rsync.html) and `vagrant rsync-auto` (https://www.vagrantup.com/docs/cli/rsync-auto.html).

That being said, I just notice those commands are not shown in the `vagrant --help` output. You have to run `vagrant list-commands` to see documentations for those commands among others...

**Comment by jesusaurus** [comment]
Thanks, I had no idea those commands existed because they weren't listed in the `vagrant --help` output.
